# Generated by Django 2.2.13 on 2022-06-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220625_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='price_rrc',
            field=models.PositiveIntegerField(verbose_name='Рекомендуемая розничная цена'),
        ),
    ]
