# Generated by Django 4.0.3 on 2022-07-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='delivery_price',
            field=models.PositiveIntegerField(default=True, verbose_name='Цена доставки'),
        ),
    ]
